basePath: /api
definitions:
  handlers.Address:
    properties:
      address:
        type: string
      address_type:
        type: integer
      district:
        type: string
      employee_id:
        type: string
      owner_type:
        type: integer
      postal_code:
        type: string
      province:
        type: string
      sub_district:
        type: string
    type: object
  handlers.Department:
    properties:
      created_date:
        type: string
      department_id:
        type: integer
      department_name:
        type: string
      updated_date:
        type: string
    type: object
  handlers.District:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      district_id:
        type: integer
      name_en:
        type: string
      name_th:
        type: string
      province_id:
        type: integer
      updated_at:
        type: string
    type: object
  handlers.Employee:
    properties:
      address:
        allOf:
        - $ref: '#/definitions/handlers.Address'
        description: Employee address
      birth_date:
        type: string
      company_email:
        type: string
      created_by:
        type: string
      created_date:
        type: string
      custom_attributes:
        type: string
      department:
        type: string
      employee_id:
        type: string
      employment_type:
        type: integer
      first_name_en:
        type: string
      first_name_th:
        type: string
      gender:
        type: integer
      is_active:
        type: boolean
      last_name_en:
        type: string
      last_name_th:
        type: string
      nationality:
        type: string
      nick_name_en:
        type: string
      nick_name_th:
        type: string
      personal_email:
        type: string
      phone_number:
        type: string
      photo:
        type: string
      position:
        type: string
      remark:
        type: string
      start_work_date:
        type: string
      status:
        type: integer
      tax_id:
        type: string
      title:
        type: integer
      updated_by:
        type: string
      updated_date:
        type: string
    type: object
  handlers.EmployeeListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/handlers.Employee'
        type: array
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  handlers.Geography:
    properties:
      geography_id:
        type: integer
      name:
        type: string
    type: object
  handlers.Province:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      geography_id:
        type: integer
      province_id:
        type: integer
      province_name_en:
        type: string
      province_name_th:
        type: string
      updated_at:
        type: string
    type: object
  handlers.SubDistrict:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      district_id:
        type: integer
      lat:
        type: string
      long:
        type: string
      name_en:
        type: string
      name_th:
        type: string
      sub_district_id:
        type: integer
      updated_at:
        type: string
      zip_code:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for managing employees with bilingual support and location dropdown
    data
  title: Employee Management & Location API
  version: "1.0"
paths:
  /departments:
    get:
      description: Get list of all departments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.Department'
            type: array
        "500":
          description: Server error
          schema:
            type: string
      summary: Get all departments
      tags:
      - department
  /districts:
    get:
      description: Get list of districts, optionally filtered by province_id
      parameters:
      - description: Province ID to filter districts
        in: query
        name: province_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.District'
            type: array
        "500":
          description: Server error
          schema:
            type: string
      summary: Get districts
      tags:
      - location
  /employee:
    post:
      consumes:
      - application/json
      description: Create a new employee with bilingual information
      parameters:
      - description: Employee object
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/handlers.Employee'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.Employee'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Create a new employee
      tags:
      - employee
  /employee/{id}:
    delete:
      description: Delete employee by ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Delete employee
      tags:
      - employee
    get:
      description: Get employee details by employee ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Employee'
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Get employee by ID
      tags:
      - employee
    put:
      consumes:
      - application/json
      description: Update employee information by ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      - description: Employee object
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/handlers.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Employee'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Update employee
      tags:
      - employee
  /employees:
    get:
      description: Get paginated list of employees with sorting and search
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: page_size
        type: integer
      - default: created_date
        description: Sort field
        in: query
        name: sort_by
        type: string
      - default: asc
        description: Sort order (asc/desc)
        in: query
        name: sort_order
        type: string
      - description: Search term
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.EmployeeListResponse'
        "500":
          description: Server error
          schema:
            type: string
      summary: Get list of employees
      tags:
      - employee
  /geographies:
    get:
      description: Get list of all geographies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.Geography'
            type: array
        "500":
          description: Server error
          schema:
            type: string
      summary: Get all geographies
      tags:
      - location
  /provinces:
    get:
      description: Get list of provinces, optionally filtered by geography_id
      parameters:
      - description: Geography ID to filter provinces
        in: query
        name: geography_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.Province'
            type: array
        "500":
          description: Server error
          schema:
            type: string
      summary: Get provinces
      tags:
      - location
  /subdistricts:
    get:
      description: Get list of sub-districts, optionally filtered by district_id
      parameters:
      - description: District ID to filter sub-districts
        in: query
        name: district_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.SubDistrict'
            type: array
        "500":
          description: Server error
          schema:
            type: string
      summary: Get sub-districts
      tags:
      - location
swagger: "2.0"
