basePath: /api
definitions:
  handlers.Employee:
    properties:
      birth_date:
        type: string
      company_email:
        type: string
      created_by:
        type: string
      created_date:
        type: string
      custom_attributes:
        type: string
      department:
        type: string
      employee_id:
        type: string
      employment_type:
        type: integer
      first_name_en:
        type: string
      first_name_th:
        type: string
      gender:
        type: integer
      is_active:
        type: boolean
      last_name_en:
        type: string
      last_name_th:
        type: string
      nationality:
        type: string
      nick_name_en:
        type: string
      nick_name_th:
        type: string
      phone_number:
        type: string
      photo:
        type: string
      position:
        type: string
      remark:
        type: string
      start_work_date:
        type: string
      status:
        type: integer
      tax_id:
        type: string
      title:
        type: integer
      updated_by:
        type: string
      updated_date:
        type: string
    type: object
  handlers.EmployeeListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/handlers.Employee'
        type: array
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for managing employees with bilingual support
  title: Employee Management API
  version: "1.0"
paths:
  /employee:
    post:
      consumes:
      - application/json
      description: Create a new employee with bilingual information
      parameters:
      - description: Employee object
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/handlers.Employee'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.Employee'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Create a new employee
      tags:
      - employee
  /employee/{id}:
    delete:
      description: Delete employee by ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Delete employee
      tags:
      - employee
    get:
      description: Get employee details by employee ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Employee'
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Get employee by ID
      tags:
      - employee
    put:
      consumes:
      - application/json
      description: Update employee information by ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      - description: Employee object
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/handlers.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Employee'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Update employee
      tags:
      - employee
  /employees:
    get:
      description: Get paginated list of employees with sorting and search
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: page_size
        type: integer
      - default: created_date
        description: Sort field
        in: query
        name: sort_by
        type: string
      - default: asc
        description: Sort order (asc/desc)
        in: query
        name: sort_order
        type: string
      - description: Search term
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.EmployeeListResponse'
        "500":
          description: Server error
          schema:
            type: string
      summary: Get list of employees
      tags:
      - employee
swagger: "2.0"
